// <auto-generated />
using System;
using Login.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Login.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251026222731_SetNullOnEntrenadorDelete")]
    partial class SetNullOnEntrenadorDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Login.Domain.Entities.Alumno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("altura_cm")
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid?>("entrenador_id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("fecha_nacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("notas")
                        .HasColumnType("text");

                    b.Property<decimal>("peso_kg")
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.HasIndex("entrenador_id");

                    b.ToTable("Alumno", (string)null);
                });

            modelBuilder.Entity("Login.Domain.Entities.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.HasKey("Id");

                    b.ToTable("Rol", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("84ca0972-519a-4207-81cf-2912595a88fa"),
                            nombre = "Admin"
                        },
                        new
                        {
                            Id = new Guid("d13e9d2f-f4c9-446e-a69d-3c1c5db142b6"),
                            nombre = "Entrenador"
                        },
                        new
                        {
                            Id = new Guid("abbeee1d-f039-4349-8a3f-456a90c76838"),
                            nombre = "Alumno"
                        });
                });

            modelBuilder.Entity("Login.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("actualizado_en")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("celular")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("creado_en")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("rol_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("rol_id");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Login.Domain.Entities.Alumno", b =>
                {
                    b.HasOne("Login.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Alumno")
                        .HasForeignKey("Login.Domain.Entities.Alumno", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Login.Domain.Entities.Usuario", "Entrenador")
                        .WithMany("AlumnosEntrenados")
                        .HasForeignKey("entrenador_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Entrenador");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Login.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Login.Domain.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("rol_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Login.Domain.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Login.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Alumno");

                    b.Navigation("AlumnosEntrenados");
                });
#pragma warning restore 612, 618
        }
    }
}
